#!/usr/bin/env bash

echo "Formatting code with clang-format..."

MINIMUM=16
VERSION=$(clang-format --version | sed 's/^.* \([0-9]*\)\..*$/\1/g')

echo "clang-format major version is ${VERSION}"

if [ "${VERSION}" -lt "${MINIMUM}" ]; then
    echo "Warning: This project requires clang format ${MINIMUM}. Output may be invalid!"
fi

REPO_PATH=$(git rev-parse --show-toplevel)
find "${REPO_PATH}/src" \( -iname '*.hpp' -o -iname '*.cpp' \) \
     -exec clang-format --style=file:"${REPO_PATH}/.clang-format" -i {} +
