name: Documentation
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Obtain dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build doxygen
          pip3 install --user sphinx breathe furo
      - name: Configure CMake
        run: cmake -GNinja -B ${{github.workspace}}/build -S ${{github.workspace}}/docs -DCMAKE_MODULE_PATH=${{github.workspace}}/cmake
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target docs_html
      - name: Publish
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/docs/'
          destination_repo: 'planetincremental/docs'
          destination_folder: '.'
          destination_branch: 'master'
          user_email: 'publish@planetincremental.github.io'
          user_name: 'publish-action'
          commit_message: 'auto-publishing changes'
