name: Web release
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
env:
  BUILD_TYPE: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Obtain dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xorg-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev ninja-build
      - uses: mymindstorm/setup-emsdk@v12
      - name: Configure CMake
        run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPLATFORM=Web -DENABLE_UT=OFF -GNinja
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Publish
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/bin/*'
          destination_repo: 'planetincremental/planetincremental.github.io'
          destination_folder: '.'
          destination_branch: 'master'
          user_email: 'publish@planetincremental.github.io'
          user_name: 'publish-action'
          commit_message: 'auto-publishing changes'
